# Generated by Django 2.1.5 on 2020-07-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender', max_length=10, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=10, null=True)),
                ('genotype', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('image_img', models.ImageField(blank=True, null=True, upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('terminal_illness', models.CharField(blank=True, choices=[('Cancer', 'Cancer'), ('Azemia', 'Azemia'), ('Parkinson', 'Parkinson'), ('Diabetis', 'Diabetis'), ('Arthritis', 'Arthritis'), ('Others', 'Others')], default='', max_length=10, null=True)),
                ('virial_dieseases', models.CharField(blank=True, choices=[('Corona', 'Corona'), ('Ebola', 'Ebola'), ('HIV', 'HIV'), ('Small Pox', 'SmallPox'), ('Influenza', 'Influenza'), ('Others', 'Others')], default='', max_length=10, null=True)),
                ('Common_Illness', models.CharField(blank=True, choices=[('Malaria', 'Malaria'), ('Fever', 'Fever'), ('Diarrhea', 'Diarrhea'), ('Common Cough', 'Common_Cough'), ('Cold', 'Cold'), ('Food poisoning', 'Food_poisoning'), ('Others', 'Others')], default='', max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
